name: Tests on Ubuntu runner

on:
  push:
    branches:
      - "**"

env:
  MAIN_BRANCH_URL: "https://raw.githubusercontent.com/liquidcarbon/puppy/main/"
  PYTHONIOENCODING: "utf8" # https://github.com/pallets/click/issues/2121

jobs:
  puppy-bash-default:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'nogha')"
    steps:
      - name: Set up custom PATH
        run: echo "PATH=$HOME/.pixi/bin:$PATH" >> $GITHUB_ENV
      - name: Install default puppy
        run: |
          sleep 9;  # give it time to update MAIN_BRANCH_URL
          curl -fsSL $MAIN_BRANCH_URL/pup.sh | bash
      - name: new env with pup new
        run: |
          pup new t1
          pup add t1 "cowsay<6"
      - name: new env with pup add
        run: |
          pup add t2 cowsay httpx
          pup list
