name: Tests on Windows runner

on:
  push:
    branches:
      - "**"

env:
  MAIN_BRANCH_URL: "https://raw.githubusercontent.com/liquidcarbon/puppy/main/"
  PYTHONIOENCODING: "utf8" # https://github.com/pallets/click/issues/2121
  PATH: "%USERPROFILE%\\.pixi\\bin;%PATH%"

jobs:
  puppy-win-311:
    runs-on: windows-latest
    if: "!contains(github.event.head_commit.message, 'nogha')"
    steps:
      - name: Set up custom PATH
        run: echo "PATH=%USERPROFILE%\.pixi\bin;%PATH%" >> $GITHUB_ENV; echo $PATH
      - name: Install puppy 3.11
        run: |
          sleep 9;  # give it time to update MAIN_BRANCH_URL
          & ([scriptblock]::Create((iwr -useb $env:MAIN_BRANCH_URL/pup.ps1).Content)) 3.11
      - name: new env with pup new
        run: |
          pup new t1
          pup add t1 "cowsay<6"
      - name: new env with pup add
        run: |
          pup add t2 cowsay httpx
          pup list
