name: Tests on Windows runner

on:
  push:
    branches:
      - "**"

env:
  MAIN_BRANCH_URL: "https://raw.githubusercontent.com/liquidcarbon/puppy/main/"
  PYTHONIOENCODING: "utf8" # https://github.com/pallets/click/issues/2121
  PATH: "C:\\Users\\runneradmin\\.pixi\\bin"

jobs:
  puppy-win-311:
    runs-on: windows-latest
    if: "!contains(github.event.head_commit.message, 'nogha')"
    steps:
      - name: Check PATH
        run: echo $PATH; echo $GITHUB_ENV
      - name: Install puppy 3.11
        run: |
          sleep 9;  # give it time to update MAIN_BRANCH_URL
          & ([scriptblock]::Create((iwr -useb $env:MAIN_BRANCH_URL/pup.ps1).Content)) 3.11
      - name: new env with pup new
        run: |
          pup new t1/with/nesting
          pup add t1/with/nesting "cowsay<6"
      - name: new env with pup add from another folder
        run: |
          cd t1
          pup add t2 cowsay requests
          pup list
      - name: pup remove
        run: |
          pup remove t1/with/nesting cowsay
          pup list
      - name: import pup with fetch
        run: |
          pixi run python -c 'import pup; pup.fetch("t1/with/nesting", "httpx"); import httpx; print(httpx.get("https://example.com"))'
      - name: pup update after deleting pixi.exe
        run: |
          rm C:\\Users\\runneradmin\\.pixi\\bin\\pixi.exe
          pup update
